### ISSUE TITLE
Upgrading to 2.0.0 causes server RuntimeConfig variables to be type "unknown"

### ISSUE THREAD

**Issue by liamb0t** [Baroshem/nuxt-security#544]
Nuxt version: 3.13.2
Nuxt-security version: 1.4.3

I'm not sure if this is a bug or it's just an issue with my config, so I'll just ask it as a question. 

But basically I'm trying to upgrade our Nuxt-security module from 1.4.3 --> 2.0.0. But I'm getting type errors where RuntimeConfig variables are being cast as type `unknown`, but they are expected to be type `string`. 

```
error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.
```

This is only seems to be the case though for files in our app `server/api` folders. RuntimeConfig variables used outside of the server/apis folders don't seem to throw this error. I tried deleting the server folder and then running again with the upgrade and it seems the errors disappear. 

Also on Nuxt-security version 1.4.3, then these errors don't occur. Only when I upgrade to 2.0.0. 

Could it be related to this? https://github.com/Baroshem/nuxt-security/issues/319

Thank you in advance.

**Comment by liamb0t** [comment]
Bump

**Comment by vejja** [comment]
Hi @liamb0t 
Could you provide a minimal repro?

**Comment by liamb0t** [comment]
@vejja 

I could not make a minimal reproduction of the error unfortunately . Is there anything else I could do?

**Comment by vejja** [comment]
Would you be able to share your nuxt.config.ts and your tsconfig.json ?

**Comment by liamb0t** [comment]
Shared nuxt.config.ts 

```
import { hrtime } from 'node:process'
const isDev = process.env.NODE_ENV === 'development'

export default defineNuxtConfig({
  app: {
    head: {
      viewport: 'width=device-width, initial-scale=1, viewport-fit=cover'
    }
  },
  modules: [
    '@nuxt/devtools',
    'nuxt-directus',
    '@pinia/nuxt',
    '@vueuse/nuxt',
    'nuxt-security',
    '@nuxtjs/tailwindcss',
    '@nuxt/test-utils/module',
    '@nuxtjs/device'
  ],
  build: {
    transpile: [
      '@fortawesome/vue-fontawesome'
    ]
  },
  security: {
    headers: {
      crossOriginEmbedderPolicy: isDev ? 'unsafe-none' : 'credentialless',
      contentSecurityPolicy: {
        'img-src': ['\'self\'', 'data:', 'https://website.com'],
        // allow embedding on website.com
        'frame-ancestors': ['\'self\'', 'https://website.com']
      },
      // Mabpox API URL restriction needs to now the referrer
      referrerPolicy: 'no-referrer-when-downgrade',
      permissionsPolicy: {
        geolocation: ['*']
      }
    }
  },
  runtimeConfig: {
    public: {
      MAPBOX_ACCESS_TOKEN: process.env.MAPBOX_ACCESS_TOKEN,
      GOOGLE_TILES_API_KEY: process.env.GOOGLE_TILES_API_KEY,
      CMS_GOOGLE_OAUTH_CLIENT_ID: process.env.CMS_GOOGLE_OAUTH_CLIENT_ID,
      VERCEL_ENV: process.env.VERCEL_ENV,
      BUILD_TIME: hrtime.bigint().toString()
    }
  },
  directus: {
    url: 'https://website.directus.app/'
  },
  devtools: {
    enabled: isDev,

    timeline: {
      enabled: true
    }
  },
  css: [
    '@fortawesome/fontawesome-svg-core/styles.css',
    'mapbox-gl/dist/mapbox-gl.css'
  ],
  typescript: {
    typeCheck: isDev ? true : false
  },
  vue: {
    compilerOptions: {
      isCustomElement: tag =>
        ['model-viewer', 'dotlottie-player', 'gmp-map-3d'].includes(tag)
    }
  }
})
```

App nuxt.config.ts


```
export default defineNuxtConfig({
  telemetry: false,
  extends: [
    '../../packages/shared',
    '../../packages/ui-lib'
  ],
  routeRules: {
    '**/editor/**': {
      security: {
        headers: {
          contentSecurityPolicy: {
            'script-src': ['\'wasm-unsafe-eval\'', '\'self\'', 'https:', '\'unsafe-inline\'', '\'strict-dynamic\'', '\'nonce-{{nonce}}\'']
          }
        }
      }
    }
  },
  runtimeConfig: {
    DIRECTUS_API_TOKEN: process.env.DIRECTUS_API_TOKEN || '',
    public: {
      VERCEL_ANALYTICS_API_KEY: process.env.VERCEL_ANALYTICS_API_KEY,
      VERCEL_PROJECT_ID: process.env.VERCEL_PROJECT_ID,
      VERCEL_TEAM_ID: process.env.VERCEL_TEAM_ID,
      EDITOR_WEBSOCKET_TOKEN: process.env.EDITOR_WEBSOCKET_TOKEN
    }
  },
  directus: {
    autoRefresh: true
  },
  typescript: {
    tsConfig: {
      exclude: [
        '../public/Cesium/**/*'
      ]
    }
  },
  nitro: {
    routeRules: {
      '/api/analytics/**': { proxy: { to: 'https://vercel.com/api/**' } }
    }
  },
  vite: {
    define: {
      CESIUM_BASE_URL: JSON.stringify('/Cesium')
    },
    server: {
      proxy: {
        '/api/runtime-editor': {
          target: 'https://cms.website.dev',
          changeOrigin: true
        }
      }
    }
  }
})
```

App tsconfig.json 


```
// Generated by nuxi
{
  "compilerOptions": {
    "paths": {
      "nitropack": [
        "../../../node_modules/nitropack"
      ],
      "defu": [
        "../../../node_modules/defu"
      ],
      "h3": [
        "../../../node_modules/h3"
      ],
      "consola": [
        "../../../node_modules/consola"
      ],
      "ofetch": [
        "../../../node_modules/ofetch"
      ],
      "@unhead/vue": [
        "../../../node_modules/@unhead/vue"
      ],
      "@nuxt/devtools": [
        "../../../node_modules/@nuxt/devtools"
      ],
      "vue": [
        "../../../node_modules/vue"
      ],
      "@vue/runtime-core": [
        "../../../node_modules/@vue/runtime-core"
      ],
      "@vue/compiler-sfc": [
        "../../../node_modules/@vue/compiler-sfc"
      ],
      "vue-router": [
        "../../../node_modules/vue-router"
      ],
      "vue-router/auto-routes": [
        "../../../node_modules/vue-router/vue-router-auto-routes"
      ],
      "unplugin-vue-router/client": [
        "../../../node_modules/unplugin-vue-router/client"
      ],
      "@nuxt/schema": [
        "../../../node_modules/@nuxt/schema"
      ],
      "nuxt": [
        "../../../node_modules/nuxt"
      ],
      "~": [
        ".."
      ],
      "~/*": [
        "../*"
      ],
      "@": [
        ".."
      ],
      "@/*": [
        "../*"
      ],
      "~~": [
        ".."
      ],
      "~~/*": [
        "../*"
      ],
      "@@": [
        ".."
      ],
      "@@/*": [
        "../*"
      ],
      "assets": [
        "../assets"
      ],
      "assets/*": [
        "../assets/*"
      ],
      "public": [
        "../public"
      ],
      "public/*": [
        "../public/*"
      ],
      "#app": [
        "../../../node_modules/nuxt/dist/app"
      ],
      "#app/*": [
        "../../../node_modules/nuxt/dist/app/*"
      ],
      "vue-demi": [
        "../../../node_modules/nuxt/dist/app/compat/vue-demi"
      ],
      "pinia": [
        "../../../node_modules/pinia/dist/pinia"
      ],
      "#vue-router": [
        "../../../node_modules/vue-router"
      ],
      "#imports": [
        "./imports"
      ],
      "#app-manifest": [
        "./manifest/meta/dev.json"
      ],
      "#build": [
        "."
      ],
      "#build/*": [
        "./*"
      ],
      "#components": [
        "./components"
      ]
    },
    "esModuleInterop": true,
    "skipLibCheck": true,
    "target": "ESNext",
    "allowJs": true,
    "resolveJsonModule": true,
    "moduleDetection": "force",
    "isolatedModules": true,
    "verbatimModuleSyntax": true,
    "strict": true,
    "noUncheckedIndexedAccess": false,
    "forceConsistentCasingInFileNames": true,
    "noImplicitOverride": true,
    "module": "preserve",
    "noEmit": true,
    "lib": [
      "ESNext",
      "dom",
      "dom.iterable",
      "webworker"
    ],
    "jsx": "preserve",
    "jsxImportSource": "vue",
    "types": [],
    "moduleResolution": "Bundler",
    "useDefineForClassFields": true,
    "noImplicitThis": true,
    "allowSyntheticDefaultImports": true
  },
  "include": [
    "./nuxt.d.ts",
    "../.config/nuxt.*",
    "../**/*",
    "../../../packages/shared/**/*",
    "../../../packages/ui-lib/**/*",
    "../../../node_modules/@nuxt/devtools/runtime",
    "../../../node_modules/@nuxt/devtools/dist/runtime",
    "../../../node_modules/nuxt-directus/runtime",
    "../../../node_modules/nuxt-directus/dist/runtime",
    "../../../node_modules/@pinia/nuxt/runtime",
    "../../../node_modules/@pinia/nuxt/dist/runtime",
    "../../../node_modules/@vueuse/nuxt/runtime",
    "../../../node_modules/@vueuse/nuxt/dist/runtime",
    "../../../node_modules/nuxt-security/runtime",
    "../../../node_modules/nuxt-security/dist/runtime",
    "../../../node_modules/@nuxtjs/tailwindcss/runtime",
    "../../../node_modules/@nuxtjs/tailwindcss/dist/runtime",
    "../../../../../../runtime",
    "../../../../../../dist/runtime",
    "../../../node_modules/@nuxtjs/device/runtime",
    "../../../node_modules/@nuxtjs/device/dist/runtime",
    "..",
    "../../../node_modules/nuxt/dist/app",
    "../../../node_modules/nuxt/dist/app/compat/vue-demi",
    "../../../node_modules/pinia/dist/pinia",
    "../../../node_modules/vue-router/dist/vue-router.node"
  ],
  "exclude": [
    "../public/Cesium/**/*",
    "../dist",
    "../node_modules",
    "../../../node_modules",
    "../../../node_modules/nuxt/node_modules",
    "../../../packages/shared/node_modules",
    "../../../packages/ui-lib/node_modules",
    "../../../node_modules/@nuxt/devtools/runtime/server",
    "../../../node_modules/@nuxt/devtools/dist/runtime/server",
    "../../../node_modules/nuxt-directus/runtime/server",
    "../../../node_modules/nuxt-directus/dist/runtime/server",
    "../../../node_modules/@pinia/nuxt/runtime/server",
    "../../../node_modules/@pinia/nuxt/dist/runtime/server",
    "../../../node_modules/@vueuse/nuxt/runtime/server",
    "../../../node_modules/@vueuse/nuxt/dist/runtime/server",
    "../../../node_modules/nuxt-security/runtime/server",
    "../../../node_modules/nuxt-security/dist/runtime/server",
    "../../../node_modules/@nuxtjs/tailwindcss/runtime/server",
    "../../../node_modules/@nuxtjs/tailwindcss/dist/runtime/server",
    "../../../../../../runtime/server",
    "../../../../../../dist/runtime/server",
    "../../../node_modules/@nuxtjs/device/runtime/server",
    "../../../node_modules/@nuxtjs/device/dist/runtime/server",
    "../.output"
  ]
}
```

**Comment by Baroshem** [comment]
Hey @liamb0t 

I am not sure what can be causing it. If I understand correctly, it works if you remove server directory right?

The changes between 1.4.3 to 2.0.0 are quite big to be honest (even including migrating Nuxt versions) so there could be things that we missed.

**Comment by liamb0t** [comment]
@Baroshem 

Yes, it works fine if I remove the server directory. Also, we use these RuntimeConfig variables outside the server directories and these don't seem to throw any errors at runtime. Only those used in the server directories.

<img width="1098" alt="Screenshot 2024-11-14 at 9 58 46" src="https://github.com/user-attachments/assets/4581d942-f664-46a0-aa88-438d5ec506e8">

**Comment by liamb0t** [comment]
@vejja 

Yes, you are right, there is also a tsconfig.json file in the server folder that extends the tsconfig.server.json file in the .nuxt folder. This is the tsconfig.server.json file:

```
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noEmit": true,
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "allowJs": true,
    "resolveJsonModule": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true,
    "jsxFactory": "h",
    "jsxFragmentFactory": "Fragment",
    "paths": {
      "#imports": [
        "./types/nitro-imports"
      ],
      "~/*": [
        "../*",
        "../*"
      ],
      "@/*": [
        "../*",
        "../*"
      ],
      "~~/*": [
        "../*",
        "../*"
      ],
      "@@/*": [
        "../*",
        "../*"
      ],
      "nitropack": [
        "../../../node_modules/nitropack"
      ],
      "defu": [
        "../../../node_modules/defu"
      ],
      "h3": [
        "../../../node_modules/h3"
      ],
      "consola": [
        "../../../node_modules/consola"
      ],
      "ofetch": [
        "../../../node_modules/ofetch"
      ],
      "@unhead/vue": [
        "../../../node_modules/@unhead/vue"
      ],
      "@nuxt/devtools": [
        "../../../node_modules/@nuxt/devtools"
      ],
      "vue": [
        "../../../node_modules/vue"
      ],
      "@vue/runtime-core": [
        "../../../node_modules/@vue/runtime-core"
      ],
      "@vue/compiler-sfc": [
        "../../../node_modules/@vue/compiler-sfc"
      ],
      "vue-router": [
        "../../../node_modules/vue-router"
      ],
      "vue-router/auto-routes": [
        "../../../node_modules/vue-router/vue-router-auto-routes"
      ],
      "unplugin-vue-router/client": [
        "../../../node_modules/unplugin-vue-router/client"
      ],
      "@nuxt/schema": [
        "../../../node_modules/@nuxt/schema"
      ],
      "nuxt": [
        "../../../node_modules/nuxt"
      ],
      "#internal/nuxt/paths": [
        "../../../node_modules/nuxt/dist/core/runtime/nitro/paths"
      ],
      "~": [
        "./.."
      ],
      "@": [
        "./.."
      ],
      "~~": [
        "./.."
      ],
      "@@": [
        "./.."
      ],
      "assets": [
        "../assets"
      ],
      "assets/*": [
        "../assets/*"
      ],
      "public": [
        "../public"
      ],
      "public/*": [
        "../public/*"
      ],
      "pinia": [
        "../../../node_modules/pinia/dist/pinia"
      ],
      "#vue-router": [
        "./vue-router"
      ]
    },
    "lib": [
      "esnext",
      "webworker",
      "dom.iterable"
    ]
  },
  "include": [
    "./types/nitro-nuxt.d.ts",
    "../../../node_modules/@nuxt/devtools/runtime/server",
    "../../../node_modules/nuxt-directus/runtime/server",
    "../../../node_modules/@pinia/nuxt/runtime/server",
    "../../../node_modules/@vueuse/nuxt/runtime/server",
    "../../../node_modules/nuxt-security/runtime/server",
    "../../../node_modules/@nuxtjs/tailwindcss/runtime/server",
    "../../../../../../runtime/server",
    "../../../node_modules/@nuxtjs/device/runtime/server",
    "./types/nitro.d.ts",
    "../**/*",
    "../server/**/*"
  ],
  "exclude": [
    "../node_modules",
    "../../../node_modules",
    "../../../node_modules/nuxt/node_modules",
    "../../../packages/shared/node_modules",
    "../../../packages/ui-lib/node_modules",
    "../dist"
  ]
}
```

**Comment by vejja** [comment]
If you remove the Nuxt-security module, the TS errors disappear, right?

**Comment by vejja** [comment]
Sorry to add one more check: if you run `npm run prepare`, the TS errors are still there?

**Comment by liamb0t** [comment]
> If you remove the Nuxt-security module, the TS errors disappear, right?

Sorry, where should I remove it from?

**Comment by vejja** [comment]
> > If you remove the Nuxt-security module, the TS errors disappear, right?
> 
> Sorry, where should I remove it from?

nuxt.config.ts > modules array

**Comment by liamb0t** [comment]
> > > If you remove the Nuxt-security module, the TS errors disappear, right?
> > 
> > 
> > Sorry, where should I remove it from?
> 
> nuxt.config.ts > modules array

Yes, if I remove the module the errors disappear

**Comment by vejja** [comment]
Ok, can you add it back and then run `npm run prepare` ? Just to check if the tsconfig gets regenerated

**Comment by liamb0t** [comment]
npm run prepare

> prepare
> npx nuxi prepare

ℹ Using 2024-04-03 as fallback compatibility date.                                                                                       10:04:22 AM
✔ Types generated in .nuxt    

Looks like tsconfigs do not get regenerated after prepare. I can only see nuxt-security module appear in tsconfig after running dev command. 

```
{
  "name": "monorepo",
  "private": true,
  "type": "module",
  "packageManager": "bun@1.1.26",
  "scripts": {
    "build": "nx run-many -t build",
    "dev": "nx run-many -t dev",
    "dev:cms": "nx dev cms",
    "dev:webview": "nx dev webview",
    "generate": "nx run-many -t generate",
    "lint": "eslint .",
    "lint:fix": "eslint --fix .",
    "typecheck": "nx run-many -t typecheck",
    "transform-tokens": "bun run --filter design-system transform-tokens",
    "generate-surrogates": "bun run --filter editor-surrogates generate-surrogates",
    "test": "nx run-many -t test",
    "prepare": "husky"
  },
  "devDependencies": {
    "@nuxt/eslint-config": "0.6.1",
    "@nuxt/test-utils": "3.14.4",
    "@nuxtjs/device": "3.2.4",
    "@nuxtjs/i18n": "8.5.6",
    "@nuxtjs/tailwindcss": "6.12.2",
    "@stylistic/eslint-plugin": "2.10.1",
    "@types/bun": "1.1.13",
    "@types/google.maps": "3.58.1",
    "@types/qrcode": "1.5.5",
    "@types/three": "0.169.0",
    "@types/uuid": "10.0.0",
    "@vite-pwa/nuxt": "0.10.6",
    "@vitest/ui": "2.1.4",
    "@vue/test-utils": "2.4.6",
    "@vueuse/nuxt": "11.1.0",
    "colord": "2.9.3",
    "eslint": "9.14.0",
    "eslint-plugin-tailwindcss": "3.17.5",
    "eslint-plugin-vuejs-accessibility": "2.4.1",
    "happy-dom": "15.11.1",
    "husky": "9.1.6",
    "lint-staged": "15.2.10",
    "nuxt": "3.13.2",
    "nuxt-directus": "5.6.1",
    "nuxt-security": "2.0.0",
    "nx": "20.1.0",
    "playwright-core": "1.47.2",
    "protobufjs-cli": "1.1.3",
    "style-dictionary": "4.1.4",
    "tailwindcss": "3.4.14",
    "typescript": "5.6.3",
    "vitest": "2.1.4",
    "vue": "3.5.12",
    "vue-tsc": "2.1.10"
  },
  "dependencies": {
    "@dotlottie/player-component": "2.7.12",
    "@fortawesome/fontawesome-svg-core": "6.6.0",
    "@fortawesome/free-brands-svg-icons": "6.6.0",
    "@fortawesome/free-regular-svg-icons": "6.6.0",
    "@fortawesome/free-solid-svg-icons": "6.6.0",
    "@fortawesome/vue-fontawesome": "3.0.8",
    "@google/model-viewer": "3.5.0",
    "@googlemaps/js-api-loader": "1.16.8",
    "@headlessui/vue": "1.7.23",
    "@heroicons/vue": "2.1.5",
    "@inworld/nodejs-sdk": "1.16.0",
    "@inworld/web-core": "2.8.0",
    "@pinia/nuxt": "0.5.5",
    "@unovis/ts": "1.4.4",
    "@unovis/vue": "1.4.4",
    "@vee-validate/zod": "4.14.7",
    "@vercel/analytics": "1.3.2",
    "@vueuse/core": "11.1.0",
    "cesium": "1.123.1",
    "class-variance-authority": "0.7.0",
    "clsx": "2.1.1",
    "deck.gl": "9.0.35",
    "embla-carousel": "8.3.1",
    "embla-carousel-vue": "8.3.1",
    "http-server": "14.1.1",
    "livekit-client": "2.6.0",
    "livekit-server-sdk": "2.7.3",
    "long": "5.2.3",
    "lucide-vue-next": "0.447.0",
    "mapbox-gl": "3.7.0",
    "nuxt-swiper": "2.0.0-1",
    "pinia": "2.2.6",
    "protobufjs": "7.4.0",
    "qrcode": "1.5.4",
    "radix-vue": "1.9.9",
    "tailwind-merge": "2.5.4",
    "tailwindcss-animate": "1.0.7",
    "three": "0.170.0",
    "uuid": "10.0.0",
    "vaul-vue": "0.2.0",
    "vee-validate": "4.13.2",
    "zod": "3.23.8"
  },
  "workspaces": [
    "packages/*",
    "apps/*"
  ],
  "patchedDependencies": {
    "nuxt-directus@5.6.1": "patches/nuxt-directus@5.6.1.patch"
  }
}
```

**Comment by vejja** [comment]
It’s quite difficult for me to say.
You have a very custom setup with NX, bun and workspaces on top of Nuxt layout extensions.

In my own project, runtimeConfig types are generated when I run ‘npx nuxi prepare’. This is the step where ´unknown’ becomes ´string’, and this happens because the tsconfig file is regenerated by nuxi with the proper types.

On your end, you have the right types if you don’t use Nuxt Security, which seems to indicate that we are doing something with the types on our end. But I looked at the code and I cannot find a place where we modify the RuntimeConfig type - so I am puzzled at this stage.

I’d like to get the advice of @danielroe here.
Is there something we should do differently with types?

**Comment by liamb0t** [comment]
I cannot see runtimeConfig types in tsconfig, only in .nuxt/types/scheme.d.ts and there the type is string, not unknown. But the the module is 'nuxt/schema' without the @?

```
declare module 'nuxt/schema' {
  interface NuxtOptions {
    /**
     * Configuration for `@nuxt/devtools`
     * @see https://www.npmjs.com/package/@nuxt/devtools
     */
    ["devtools"]: typeof import("@nuxt/devtools").default extends NuxtModule<infer O> ? O : Record<string, any>
    /**
     * Configuration for `nuxt-directus`
     * @see https://www.npmjs.com/package/nuxt-directus
     */
    ["directus"]: typeof import("nuxt-directus").default extends NuxtModule<infer O> ? O : Record<string, any>
    /**
     * Configuration for `@pinia/nuxt`
     * @see https://www.npmjs.com/package/@pinia/nuxt
     */
    ["pinia"]: typeof import("@pinia/nuxt").default extends NuxtModule<infer O> ? O : Record<string, any>
    /**
     * Configuration for `@vueuse/nuxt`
     * @see https://www.npmjs.com/package/@vueuse/nuxt
     */
    ["vueuse"]: typeof import("@vueuse/nuxt").default extends NuxtModule<infer O> ? O : Record<string, any>
    /**
     * Configuration for `nuxt-security`
     * @see https://www.npmjs.com/package/nuxt-security
     */
    ["security"]: typeof import("nuxt-security").default extends NuxtModule<infer O> ? O : Record<string, any>
    /**
     * Configuration for `@nuxtjs/tailwindcss`
     * @see https://www.npmjs.com/package/@nuxtjs/tailwindcss
     */
    ["tailwindcss"]: typeof import("@nuxtjs/tailwindcss").default extends NuxtModule<infer O> ? O : Record<string, any>
    /**
     * Configuration for `@nuxt/test-utils/module`
     * @see https://www.npmjs.com/package/@nuxt/test-utils/module
     */
    ["testUtils"]: typeof import("@nuxt/test-utils/module").default extends NuxtModule<infer O> ? O : Record<string, any>
    /**
     * Configuration for `@nuxtjs/device`
     * @see https://www.npmjs.com/package/@nuxtjs/device
     */
    ["device"]: typeof import("@nuxtjs/device").default extends NuxtModule<infer O> ? O : Record<string, any>
  }
  interface NuxtConfig {
    /**
     * Configuration for `@nuxt/devtools`
     * @see https://www.npmjs.com/package/@nuxt/devtools
     */
    ["devtools"]?: typeof import("@nuxt/devtools").default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>
    /**
     * Configuration for `nuxt-directus`
     * @see https://www.npmjs.com/package/nuxt-directus
     */
    ["directus"]?: typeof import("nuxt-directus").default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>
    /**
     * Configuration for `@pinia/nuxt`
     * @see https://www.npmjs.com/package/@pinia/nuxt
     */
    ["pinia"]?: typeof import("@pinia/nuxt").default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>
    /**
     * Configuration for `@vueuse/nuxt`
     * @see https://www.npmjs.com/package/@vueuse/nuxt
     */
    ["vueuse"]?: typeof import("@vueuse/nuxt").default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>
    /**
     * Configuration for `nuxt-security`
     * @see https://www.npmjs.com/package/nuxt-security
     */
    ["security"]?: typeof import("nuxt-security").default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>
    /**
     * Configuration for `@nuxtjs/tailwindcss`
     * @see https://www.npmjs.com/package/@nuxtjs/tailwindcss
     */
    ["tailwindcss"]?: typeof import("@nuxtjs/tailwindcss").default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>
    /**
     * Configuration for `@nuxt/test-utils/module`
     * @see https://www.npmjs.com/package/@nuxt/test-utils/module
     */
    ["testUtils"]?: typeof import("@nuxt/test-utils/module").default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>
    /**
     * Configuration for `@nuxtjs/device`
     * @see https://www.npmjs.com/package/@nuxtjs/device
     */
    ["device"]?: typeof import("@nuxtjs/device").default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>
    modules?: (undefined | null | false | NuxtModule<any> | string | [NuxtModule | string, Record<string, any>] | ["@nuxt/devtools", Exclude<NuxtConfig["devtools"], boolean>] | ["nuxt-directus", Exclude<NuxtConfig["directus"], boolean>] | ["@pinia/nuxt", Exclude<NuxtConfig["pinia"], boolean>] | ["@vueuse/nuxt", Exclude<NuxtConfig["vueuse"], boolean>] | ["nuxt-security", Exclude<NuxtConfig["security"], boolean>] | ["@nuxtjs/tailwindcss", Exclude<NuxtConfig["tailwindcss"], boolean>] | ["@nuxt/test-utils/module", Exclude<NuxtConfig["testUtils"], boolean>] | ["@nuxtjs/device", Exclude<NuxtConfig["device"], boolean>])[],
  }
  interface RuntimeConfig {
   app: {
      buildId: string,

      baseURL: string,

      buildAssetsDir: string,

      cdnURL: string,
   },

   DIRECTUS_API_TOKEN: string,
```

**Comment by vejja** [comment]
Is this your full `schema.d.ts` ? 
Mine is much bigger, extends `@nuxt/schema` and also defines the `PublicRuntimeConfig` interface

**Comment by liamb0t** [comment]
@vejja No, sorry, it wasn't. I edited my comment.

**Comment by vejja** [comment]
Ok so we explicitly modified `nuxt/schema` to `@nuxt/schema` as part of PR #520 which was a component of v2.
We did this to conform to @danielroe recommendations for the new `nuxt-module-builder` 
The upstream change was referenced here : https://github.com/nuxt/nuxt/issues/28332

**Comment by vejja** [comment]
> @vejja No, sorry, it wasn't. I edited my comment.

On the surface of it, it looks like now your types are correct, aren't they ?

**Comment by Baroshem** [comment]
As pointed out by @vejja this change was a recommendation from Daniel so I believe we would need to keep it this way. 

If you agree guys, I would be up for closing this ticket as `won't fix` as it is how the @nuxt/module-builder works now.

**Comment by danielroe** [comment]
this is likely not related to nuxt security. can you reproduce without the module?

**Comment by liamb0t** [comment]
Renovate managed to install v.2.0.0 successfully without me doing anything, so maybe was a problem with another module. I will close this, thanks for the help.

**Comment by liamb0t** [comment]
Renovate managed to install v.2.0.0 successfully without me doing anything, so maybe was a problem with another module. I will close this, thanks for the help.
